In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train.csv')
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [3]:
df.shape

(891, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

###**Manipulação de Colunas**

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
df.Survived

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [7]:
df.rename(columns={
    'PassengerId': 'ID_Passageniro', 
    'Survived': 'Sobreviveu', 
    'Pclass': 'Classe', 
    'Name': 'Nome', 
    'Sex': 'Sexo', 
    'Age': 'Idade', 
    'SibSp': 'Membros_Familia',
    'Parch': 'Pais_Filhos_a_Bordo',
    'Ticket': 'Bilhete', 
    'Fare': 'Valor_Passagem', 
    'Cabin':'Cabine', 
    'Embarked': 'Portao_Embarque'
}, inplace=True)
df.head(3)

,ID_Passageniro,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [8]:
dados = df.copy()
dados.head(3)

,ID_Passageniro,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [9]:
dados.drop(['ID_Passageniro'], axis=1, inplace=True)
dados.head(3)

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [10]:
dados[['Sobreviveu', 'Classe']]

     Sobreviveu  Classe
0             0       3
1             1       1
2             1       3
3             1       1
4             0       3
..          ...     ...
886           0       2
887           1       1
888           0       3
889           1       1
890           0       3

[891 rows x 2 columns]

###**Loc**

In [11]:
#Número das linhas (Valor incial até o valor final) e número das colunas (passar uma lista)
dados.loc[15:35, ['Sobreviveu', 'Nome', 'Idade']]

    Sobreviveu                                               Nome  Idade
15           1                   Hewlett, Mrs. (Mary D Kingcome)    55.0
16           0                               Rice, Master. Eugene    2.0
17           1                       Williams, Mr. Charles Eugene    NaN
18           0  Vander Planke, Mrs. Julius (Emelia Maria Vande...   31.0
19           1                            Masselmani, Mrs. Fatima    NaN
20           0                               Fynney, Mr. Joseph J   35.0
21           1                              Beesley, Mr. Lawrence   34.0
22           1                        McGowan, Miss. Anna "Annie"   15.0
23           1                       Sloper, Mr. William Thompson   28.0
24           0                      Palsson, Miss. Torborg Danira    8.0
25           1  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...   38.0
26           0                            Emir, Mr. Farred Chehab    NaN
27           0                     Fortune, Mr. Charles Alexander   19.0
28           1                      O'Dwyer, Miss. Ellen "Nellie"    NaN
29           0                                Todoroff, Mr. Lalio    NaN
30           0                           Uruchurtu, Don. Manuel E   40.0
31           1     Spencer, Mrs. William Augustus (Marie Eugenie)    NaN
32           1                           Glynn, Miss. Mary Agatha    NaN
33           0                              Wheadon, Mr. Edward H   66.0
34           0                            Meyer, Mr. Edgar Joseph   28.0
35           0                     Holverson, Mr. Alexander Oskar   42.0

In [12]:
dados.loc[:500, ['Sobreviveu', 'Nome', 'Idade']]

     Sobreviveu                                               Nome  Idade
0             0                            Braund, Mr. Owen Harris   22.0
1             1  Cumings, Mrs. John Bradley (Florence Briggs Th...   38.0
2             1                             Heikkinen, Miss. Laina   26.0
3             1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   35.0
4             0                           Allen, Mr. William Henry   35.0
..          ...                                                ...    ...
496           1                     Eustis, Miss. Elizabeth Mussey   54.0
497           0                    Shellard, Mr. Frederick William    NaN
498           0    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   25.0
499           0                                 Svensson, Mr. Olof   24.0
500           0                                   Calic, Mr. Petar   17.0

[501 rows x 3 columns]

###**Iloc**

In [14]:
#
dados.iloc[5:15, 1:4]

    Classe                                               Nome    Sexo
5        3                                   Moran, Mr. James    male
6        1                            McCarthy, Mr. Timothy J    male
7        3                     Palsson, Master. Gosta Leonard    male
8        3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9        2                Nasser, Mrs. Nicholas (Adele Achem)  female
10       3                    Sandstrom, Miss. Marguerite Rut  female
11       1                           Bonnell, Miss. Elizabeth  female
12       3                     Saundercock, Mr. William Henry    male
13       3                        Andersson, Mr. Anders Johan    male
14       3               Vestrom, Miss. Hulda Amanda Adolfina  female

###**Seleção por condição**

In [16]:
dados.loc[dados['Classe'] == 1]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [17]:
dados.loc[dados['Sexo'] == 'female']

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [18]:
dados.loc[dados['Idade'] < 18]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
7,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
16,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
850,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.0,4,2,347082,31.2750,NaN,S
852,0,3,"Boulos, Miss. Nourelain",female,9.0,1,1,2678,15.2458,NaN,C
853,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S
869,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
875,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C

In [21]:
dados.loc[(dados['Idade'] <= 18) & (dados['Sexo'] == 'male') & (dados['Sobreviveu'] != 0)]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
78,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
125,1,3,"Nicola-Yarred, Master. Elias",male,12.00,1,0,2651,11.2417,NaN,C
165,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,NaN,S
183,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S
193,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S
204,1,3,"Cohen, Mr. Gurshon ""Gus""",male,18.00,0,0,A/5 3540,8.0500,NaN,S
220,1,3,"Sunderland, Mr. Victor Francis",male,16.00,0,0,SOTON/OQ 392089,8.0500,NaN,S
261,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S
305,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
340,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S
348,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,NaN,S
407,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,NaN,S
445,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S
489,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,NaN,S
549,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,NaN,S
550,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
751,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,E121,S
755,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
788,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,NaN,S
802,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
803,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
827,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C
831,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
869,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S

In [22]:
dados.loc[(dados['Idade'] <= 18) & (dados['Sexo'] == 'male')][['Nome', 'Portao_Embarque']]

                                        Nome Portao_Embarque
7             Palsson, Master. Gosta Leonard               S
16                      Rice, Master. Eugene               Q
50                Panula, Master. Juha Niilo               S
59        Goodwin, Master. William Frederick               S
63                     Skoog, Master. Harald               S
..                                       ...             ...
834                   Allum, Mr. Owen George               S
841                 Mudd, Mr. Thomas Charles               S
844                      Culumovic, Mr. Jeso               S
850  Andersson, Master. Sigvard Harald Elias               S
869          Johnson, Master. Harold Theodor               S

[71 rows x 2 columns]

In [23]:
dados.loc[(dados['Idade'] <= 18) & (dados['Sexo'] == 'male') | (dados['Sexo'] == 'female')][['Nome', 'Portao_Embarque']]

                                                  Nome Portao_Embarque
1    Cumings, Mrs. John Bradley (Florence Briggs Th...               C
2                               Heikkinen, Miss. Laina               S
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)               S
7                       Palsson, Master. Gosta Leonard               S
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)               S
..                                                 ...             ...
880       Shelley, Mrs. William (Imanita Parrish Hall)               S
882                       Dahlberg, Miss. Gerda Ulrika               S
885               Rice, Mrs. William (Margaret Norton)               Q
887                       Graham, Miss. Margaret Edith               S
888           Johnston, Miss. Catherine Helen "Carrie"               S

[385 rows x 2 columns]

###**Filtros por srings**

In [25]:
dados[dados['Nome'].str.contains('Mr')]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [26]:
dados[dados['Nome'].str.len()>50]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
18,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
25,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
41,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,NaN,S
85,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.0,3,0,3101278,15.8500,NaN,S
142,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...",female,24.0,1,0,STON/O2. 3101279,15.8500,NaN,S
307,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.0,1,0,PC 17758,108.9000,C65,C
319,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.0,1,1,16966,134.5000,E34,C
323,1,2,"Caldwell, Mrs. Albert Francis (Sylvia Mae Harb...",female,22.0,1,1,248738,29.0000,NaN,S
383,1,1,"Holverson, Mrs. Alexander Oskar (Mary Aline To...",female,35.0,1,0,113789,52.0000,NaN,S
394,1,3,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...",female,24.0,0,2,PP 9549,16.7000,G6,S
423,0,3,"Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria ...",female,28.0,1,1,347080,14.4000,NaN,S
427,1,2,"Phillips, Miss. Kate Florence (""Mrs Kate Louis...",female,19.0,0,0,250655,26.0000,NaN,S
432,1,2,"Louch, Mrs. Charles Alexander (Alice Adelaide ...",female,42.0,1,0,SC/AH 3085,26.0000,NaN,S
518,1,2,"Angle, Mrs. William A (Florence ""Mary"" Agnes H...",female,36.0,1,0,226875,26.0000,NaN,S
556,1,1,"Duff Gordon, Lady. (Lucille Christiana Sutherl...",female,48.0,1,0,11755,39.6000,A16,C
581,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.0,1,1,17421,110.8833,C68,C
600,1,2,"Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...",female,24.0,2,1,243847,27.0000,NaN,S
608,1,2,"Laroche, Mrs. Joseph (Juliette Marie Louise La...",female,22.0,1,2,SC/Paris 2123,41.5792,NaN,C
610,0,3,"Andersson, Mrs. Anders Johan (Alfrida Konstant...",female,39.0,1,5,347082,31.2750,NaN,S
670,1,2,"Brown, Mrs. Thomas William Solomon (Elizabeth ...",female,40.0,1,1,29750,39.0000,NaN,S
759,1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.5000,B77,S
779,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.0,0,1,24160,211.3375,B3,S
799,0,3,"Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...",female,30.0,1,1,345773,24.1500,NaN,S
862,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S

In [28]:
dados[dados['Membros_Familia'].isin([1])]

,Sobreviveu,Classe,Nome,Sexo,Idade,Membros_Familia,Pais_Filhos_a_Bordo,Bilhete,Valor_Passagem,Cabine,Portao_Embarque
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
9,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
...,...,...,...,...,...,...,...,...,...,...,...
866,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
869,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
871,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
874,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S